---
- name: Cleanup
  hosts: localhost
  gather_facts: false
  vars:
    kind_cluster_name: "{{ lookup('env', 'KIND_CLUSTER_NAME') | default('velero-test', true) }}"
    ci_environment: "{{ lookup('env', 'CI') | default(false, true) }}"
  tasks:
    - name: Delete Velero namespace
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Namespace
        name: velero
      failed_when: false

    - name: Delete MinIO namespace
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Namespace
        name: minio
      failed_when: false

    - name: Delete kind cluster
      ansible.builtin.command: "kind delete cluster --name {{ kind_cluster_name }}"
      register: kind_delete
      changed_when: kind_delete.rc == 0
      failed_when: false
      when: not ci_environment
