---
- name: Converge
  hosts: localhost
  gather_facts: false
  vars:
    s3_endpoint: "http://minio.minio.svc:9000"
    s3_access_key: "minioadmin"
    s3_secret_key: "minioadmin"
    s3_bucket: "velero"
    s3_region: "minio"
    s3_force_path_style: true
    velero_use_volume_snapshots: false
  tasks:
    - name: Include velero role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
